name: sazon_urbano
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  uuid: ^4.3.3
  get_storage: ^2.1.1
  lottie: ^2.7.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.2
  cloud_firestore: ^4.15.5
  share_plus: ^7.2.1
  get: ^4.6.5
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.1.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  image: ^4.1.3
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
