import 'package:get/get.dart';

class AppTraducciones extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'es': {
      'greeting_morning': 'Buenos días',
      'greeting_afternoon': 'Buenas tardes',
      'greeting_evening': 'Buenas noches',
      'language': 'Idioma',
      'promo_best': 'Los mejores',
      'promo_restaurants': 'Restaurantes',
      'promo_region': 'de la región',
      'promo_see': 'Verlos',
      'nav_home': 'Inicio',
      'nav_create_manager': 'Crear Gerente',
      'nav_create_restaurant': 'Crear Restaurante',
      'nav_account': 'Mi Cuenta',
      'crear_restaurante': 'Crear Restaurante',
      'registrar_restaurante': 'Registra tu restaurante aquí',
      'razon_social': 'Razón Social',
      'nit': 'NIT',
      'telefono': 'Teléfono',
      'direccion': 'Dirección',
      'direccion_google_maps': 'Haz click para elegir la dirección en Google Maps.',
      'crear_gerente': 'Crear Gerente',
      'crear_gerente_descripcion': 'Crea un gerente para un restaurante',
      'nombre_completo': 'Nombre completo',
      'correo': 'Correo',
      'contrasena': 'Contraseña',
      'confirmar_contrasena': 'Confirmar Contraseña',
      'mis_restaurantes' : 'Mis Restaurantes',
      'details' : 'Detalles',
      'ver_platos' : 'Ver platos',
      'platos' : 'Platos',
      'ver_ubicacion' : 'Ver ubicación',
      'restaurantes_no_disponibles' : 'No hay restaurantes disponibles.',
      "telefono_con_valor": "Tel: @telefono",
      "mi_cuenta": "Mi Cuenta",
      "editar_perfil": "Editar Perfil",
      "cancelar": "Cancelar",
      "cerrar_sesion": "Cerrar sesión",
      "desear_cerrar_sesion": "¿Estás seguro de cerrar sesión?",
      "cerrar_sesion_boton": "Cerrar sesión",
      "guardar_cambios": "Guardar cambios",
      "seleccionar_imagen": "Seleccionar imagen",
      "tomar_foto": "Tomar foto",
      "elegir_desde_galería": "Elegir desde la galería",
      "imagen": "Imagen",
      "bienvenida_iniciar_sesion": "!Bienvenido de vuelta!",
      "crear_cuenta_empezar": "Crea una cuenta para empezar",
      "inicia_sesión_para_continuar": "Inicia sesión para continuar",
      "iniciar_sesion_boton": "Iniciar sesión",
      "no_tienes_cuenta": "¿No tienes una cuenta?",
      "crear_cuenta": "Crear cuenta",
      "tienes_cuenta": "¿Ya tienes una cuenta?",
      'error_nombre': 'Por favor ingrese el nombre',
      'error_correo': 'Por favor ingrese su correo',
      'error_correo_valido': 'Por favor ingrese un correo válido',
      'error_contrasena': 'Por favor ingrese la contraseña',
      'error_contrasena_corta': 'La contraseña debe tener al menos 6 caracteres',
      'error_confirmar_contrasena': 'Por favor confirme la contraseña',
      'error_contrasenas_no_coinciden': 'Las contraseñas no coinciden',
      'error': 'Error',
      'platillos_tipicos': 'Platillos Típicos',
      'descripcion_platillos_tipicos': 'Descubre los sabores auténticos de nuestra cultura con los mejores platillos tradicionales.',
      'restaurantes_nativos': 'Restaurantes Nativos',
      'descripcion_restaurantes_nativos': 'Apoya lo local disfrutando de comidas únicas preparadas por restaurantes auténticos de la región.',
      'saltar_contenido': 'Saltar',
      'siguiente_boton': 'Siguiente',
      'empezar_boton': 'Empezar',
      'seleccionar_idioma': 'Seleccionar idioma',
      'campos_incompletos': 'Debe completar todos los campos',
      'error_razon_social': 'Por favor ingrese la razón social',
      'error_nit': 'Por favor ingrese el NIT',
      'error_telefono': 'Por favor ingrese el teléfono',
      'error_telefono_digitos': 'El teléfono debe tener 10 dígitos',
      'error_direccion': 'Por favor ingrese la dirección',
      'error_imagen_restaurante' : 'Por favor selecciona una imagen del restaurante',
      'error_imagen_plato' : 'Por favor selecciona una imagen del plato',
      'configuracion' : 'Configuración',
      'historia_y_tradicion' : 'Historia y tradición',
      'slogan' : 'Tradición que se saborea',
      'apariencia' : 'Apariencia',
      'privacidad' : 'Privacidad',
      'politicas_de_privacidad' : 'Políticas de Privacidad',
      'ver_nuestras_politicas_de_privacidad' : 'Ver nuestras políticas de privacidad',
      'terminos_de_servicio' : 'Términos de Servicio',
      'leer_sobre_terminos_servicio' : 'Leer a cerca de nuestros términos',
      'accesibilidad' : 'Accesibilidad',
      'menu_de_accesibilidad' : 'Menú de Accesibilidad',
      'mensaje_accesibilidad' : 'Establece las opciones que te parezcan mejor para una mejor experiencia de usuario',
      'a_cerca_de' : 'A cerca de',
      'version_app' : 'Versión de App',
      'version' : '1.0.0',
      'tema_preferido' : 'Tema preferido',
      'mensaje_de_version' : 'Lanzamiento inicial de la aplicación para descubrir restaurantes y sus platillos de la región. Incluye visualización de menús.',
      'comparticion_informacion' : 'Compartición de información con terceros',
      'contenido_comparticion_informacion' : 'No vendemos tu información personal. Sin embargo, podríamos compartir datos agregados y anónimos con aliados turísticos para mejorar la calidad de nuestras recomendaciones',
      'seguridad_informacion' : 'Seguridad de la información',
      'contenido_seguridad_informacion' : 'Nos comprometemos a proteger tu información mediante medidas técnicas y organizativas. Aunque ningún sistema es 100% seguro, trabajamos constantemente para prevenir accesos no autorizados.',
      'derechos_control_datos' : 'Tus derechos y control sobre tus datos',
      'contenido_derechos_control_datos' : 'Puedes acceder, modificar o eliminar tu información personal desde la sección de perfil. También puedes solicitarnos que dejemos de utilizar tus datos en cualquier momento.',
      'cambios_terminos' : 'Cambios a estos términos',
      'contenido_cambios_terminos' : 'Nos reservamos el derecho de actualizar estos términos. Si realizamos cambios significativos, te notificaremos a través de la aplicación',
      'politicas_privacidad' : 'Políticas de Privacidad',
      'informacion_recolectamos' : 'Información que recolectamos',
      'contenido_informacion_recolectamos' : 'Recolectamos información que nos provees, incluyendo su nombre y correo electrónico.',
      'como_usamos_tu_informacion' : '¿Cómo usamos tu información personal?',
      'contenido_como_usamos_tu_informacion' : 'Usaremos tu información personal para recomendarte tus restaurantes preferidos basándonos en tu navegación por la aplicación.',
      'ultima_actualizacion_terminos' : 'Última actualización: Mayo 28 2025',
      'ultima_actualizacion_politicas' : 'Última actualización: Mayo 28 2025',
      "definiciones_titulo": "Definiciones",
      "agrandar_texto": "Agrandar texto",
      "activar_desaturacion": "Activar desaturación",
      "espaciado_texto": "Espaciado de texto",
      "respuesta_agrandar_texto": "Cuando esta opción está activada:\n\nLos textos de la aplicación aumentan su tamaño para facilitar la lectura, especialmente para personas con dificultades visuales.",
      "respuesta_activar_desaturacion": "Cuando esta opción está activada:\n\nElimina los colores vivos de la aplicación y los reemplaza por una escala de grises. Es útil para personas con sensibilidad a los colores o que prefieren una visualización más neutral.",
      "respuesta_espaciado_texto": "Cuando esta opción está activada:\n\nActiva un mayor espacio entre las letras y líneas del texto. Esto mejora la legibilidad para personas con dislexia u otras dificultades de lectura.",
      "entendido": "Entendido",
      'buscador_personalizado_restaurante' : 'Buscar restaurante',
      'buscador_personalizado_plato' : 'Buscar plato',
      'continuar': 'Continuar',
      "preferencias_visualizacion": "Preferencias de visualización",
      "que_significan_opciones": "¿Qué significan estas opciones?",
      "crear_plato_titulo": "Crear Plato",
      "crear_plato_subtitulo": "Crea un platillo aquí",
      "nombre_plato_label": "Nombre del plato",
      "nombre_plato_error": "Por favor ingrese el nombre del plato",
      "precio_label": "Precio",
      "precio_error": "Por favor ingrese el precio",
      "descripcion_label": "Descripción",
      "descripcion_error": "Por favor ingrese la descripción",
      'platos_no_disponibles' : 'No hay platos disponibles.',
      "historial_label": "Historial",
      "historial_error": "Por favor ingrese el historial",
      "crear_plato_boton": "Crear Plato",
    },
    'en': {
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'language': 'Language',
      'promo_best': 'The best',
      'promo_restaurants': 'Restaurants',
      'promo_region': 'in the region',
      'promo_see': 'See them',
      'nav_home': 'Home',
      'nav_create_manager': 'Create Manager',
      'nav_create_restaurant': 'Create Restaurant',
      'nav_account': 'My Account',
      'crear_restaurante': 'Create Restaurant',
      'registrar_restaurante': 'Register your restaurant here',
      'razon_social': 'Business Name',
      'nit': 'Tax ID',
      'telefono': 'Phone',
      'platos' : 'Dishes',
      'direccion': 'Address',
      'direccion_google_maps': 'Click to choose the address on Google Maps.',
      'crear_gerente': 'Create Manager',
      'crear_gerente_descripcion': 'Create a manager for a restaurant',
      'nombre_completo': 'Full name',
      'correo': 'Email',
      'continuar': 'Continue',
      'contrasena': 'Password',
      'confirmar_contrasena': 'Confirm Password',
      'mis_restaurantes' : 'My Restaurants',
      'details' : 'Details',
      'ver_platos' : 'See dishes',
      'seleccionar_idioma' : 'Select language',
      'buscador_personalizado_restaurante' : 'Search restaurant',
      'buscador_personalizado_plato' : 'Search dish',
      'ver_ubicacion' : 'See location',
      'restaurantes_no_disponibles' : 'There are no restaurants available.',
      'platos_no_disponibles' : 'There are no dishes available.',
      "telefono_con_valor": "Phone: @telefono",
      "mi_cuenta": "My Account",
      "editar_perfil": "Edit Profile",
      "slogan": "Tradition that is savored",
      "cancelar": "Cancel",
      'historia_y_tradicion' : 'History and tradition',
      "cerrar_sesion": "Logout",
      "desear_cerrar_sesion": "Are you sure to logout?",
      "cerrar_sesion_boton": "Logout",
      "guardar_cambios": "Save changes",
      "seleccionar_imagen": "Select image",
      "tomar_foto": "Take photo",
      'platillos_tipicos': 'Typical Dishes',
      'descripcion_platillos_tipicos': 'Discover the authentic flavors of our culture with the best traditional dishes.',
      'restaurantes_nativos': 'Native Restaurants',
      'descripcion_restaurantes_nativos': 'Support local culture by enjoying unique dishes prepared by authentic local restaurants.',
      'saltar_contenido': 'Skip',
      'siguiente_boton': 'Next',
      'empezar_boton': 'Start',
      "iniciar_sesion_boton": "Sign in",
      "elegir_desde_galería": "Choose from the gallery",
      "imagen": "Image",
      "bienvenida_iniciar_sesion": "Welcome Back!",
      "crear_cuenta_empezar": "Create an account to get started",
      "inicia_sesión_para_continuar": "Sign in to continue",
      "iniciar_sesión_boton": "Sign in",
      "no_tienes_cuenta": "Don't have an account?",
      "tienes_cuenta": "Already have an account?",
      "crear_cuenta": "Sign up",
      'error_nombre': 'Please enter the name',
      'error_correo': 'Please enter your email',
      'error_correo_valido': 'Please enter a valid email',
      'error_contrasena': 'Please enter the password',
      'error_contrasena_corta': 'Password must be at least 6 characters',
      'error_confirmar_contrasena': 'Please confirm the password',
      'error_contrasenas_no_coinciden': 'Passwords do not match',
      'error': 'Error',
      'campos_incompletos': 'All fields must be completed',
      'error_razon_social': 'Please enter the business name',
      'error_nit': 'Please enter the Tax ID',
      'error_telefono': 'Please enter the phone number',
      'error_telefono_digitos': 'Phone number must be 10 digits',
      'error_direccion': 'Please enter the address',
      'error_imagen_restaurante' : 'Please select an image of the restaurant',
      'error_imagen_plato' : 'Please select an image of the dish',
      'configuracion' : 'Settings',
      'apariencia' : 'Appearance',
      'privacidad' : 'Privacy',
      'politicas_de_privacidad' : 'Privacy Policies',
      'ver_nuestras_politicas_de_privacidad' : 'See our privacy policies',
      'terminos_de_servicio' : 'Terms of Service',
      'leer_sobre_terminos_servicio' : 'Read about our terms of service',
      'accesibilidad' : 'Accessibility',
      'menu_de_accesibilidad' : 'Accessibility Menu',
      'mensaje_accesibilidad' : 'Set the options that best suit you for a better user experience.',
      'a_cerca_de' : 'About',
      'version_app' : 'App Version',
      'version' : '1.0.0',
      'tema_preferido' : 'Favorite topic',
      'mensaje_de_version' : 'Initial launch of the app to discover restaurants and their dishes in the region. Includes menu viewing.',
      'comparticion_informacion' : 'Sharing information with third parties.',
      'contenido_comparticion_informacion' : 'We do not sell your personal information. However, we may share aggregated and anonymous data with travel partners to improve the quality of our recommendations.',
      'seguridad_informacion' : 'Information security',
      'contenido_seguridad_informacion' : 'We are committed to protecting your information through technical and organizational measures. Although no system is 100% secure, we are constantly working to prevent unauthorized access.',
      'derechos_control_datos' : 'Your rights and control over your data',
      'contenido_derechos_control_datos' : 'You can access, modify, or delete your personal information from your profile section. You can also request that we stop using your data at any time.',
      'cambios_terminos' : 'Changes to these terms',
      'contenido_cambios_terminos' : 'We reserve the right to update these terms. If we make significant changes, we will notify you through the app.',
      'politicas_privacidad' : 'Privacy Policies',
      'informacion_recolectamos' : 'Information we collect',
      'contenido_informacion_recolectamos' : 'We collect information you provide to us, including your name and email address.',
      'como_usamos_tu_informacion' : 'How do we use your personal information?',
      'contenido_como_usamos_tu_informacion' : 'We will use your personal information to recommend your favorite restaurants based on your browsing experience within the app.',
      'ultima_actualizacion_terminos' : 'Last updated: May 28, 2025',
      'ultima_actualizacion_politicas' : 'Last updated: May 28, 2025',
      "definiciones_titulo": "Definitions",
      "agrandar_texto": "Enlarge text",
      "activar_desaturacion": "Enable desaturation",
      "espaciado_texto": "Text spacing",
      "respuesta_agrandar_texto": "When this option is enabled:\n\nThe application's text increases in size to aid readability, especially for people with visual impairments.",
      "respuesta_activar_desaturacion": "When this option is enabled:\n\nRemoves vivid colors from the app and replaces them with grayscale. Useful for users sensitive to color or who prefer a neutral view.",
      "respuesta_espaciado_texto": "When this option is enabled:\n\nIncreases the space between letters and lines of text. This improves readability for people with dyslexia or other reading difficulties.",
      "entendido": "Understood",
      "preferencias_visualizacion": "Display preferences",
      "que_significan_opciones": "What do these options mean?",
      "crear_plato_titulo": "Create Dish",
      "crear_plato_subtitulo": "Create a dish here",
      "nombre_plato_label": "Dish name",
      "nombre_plato_error": "Please enter the dish name",
      "precio_label": "Price",
      "precio_error": "Please enter the price",
      "descripcion_label": "Description",
      "descripcion_error": "Please enter the description",
      "historial_label": "History",
      "historial_error": "Please enter the history",
      "crear_plato_boton": "Create Dish",
    },
  };
}